name: Cleanup Pricing Data

on:
  workflow_dispatch:
    inputs:
      cutoff:
        description: 'Fecha de corte (YYYY-MM-DD)'
        required: true
        default: '2025-10-21'
      execute:
        description: 'Ejecutar (true) o dry-run (false)'
        required: true
        default: 'false'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Run cleanup (dry-run or execute)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node scripts/cleanup_pricing.js --cutoff "${{ github.event.inputs.cutoff }}" $([ "${{ github.event.inputs.execute }}" = "true" ] && echo --execute || true)


